/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef TACTILE_DISPLAY_PB_H_INCLUDED
#define TACTILE_DISPLAY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _OutputMode {
  OutputMode_MODE_UNKNOWN = 0,
  OutputMode_VTPROTO_TACTON = 1,
  OutputMode_VTPROTO_REALTIME = 2
} OutputMode;

typedef enum _MotorType {
  MotorType_MOTOR_TYPE_UNKNOWN = 0,
  MotorType_ERM = 1,
  MotorType_LRA = 2,
  MotorType_PIEZO = 3,
  MotorType_PNEUMATIC = 4,
  MotorType_ULTRASONIC = 5
} MotorType;

/* Struct definitions */
typedef struct _AvailableConfigOptions {
  pb_callback_t motor_types;
  bool variable_voltage;
} AvailableConfigOptions;

typedef struct _ChannelConfig {
  uint32_t channel_number;
  MotorType motor_type;
  bool has_voltage;
  float voltage;
} ChannelConfig;

typedef struct _DisplayConfig {
  OutputMode output_mode;
  uint32_t number_of_channels;
  pb_callback_t channel_configs;
} DisplayConfig;

typedef struct _ReqSetOutputMode {
  OutputMode output_mode;
} ReqSetOutputMode;

typedef struct _ReqSetChannelConfig {
  bool has_channel_config;
  ChannelConfig channel_config;
} ReqSetChannelConfig;

/* Helper constants for enums */
#define _OutputMode_MIN OutputMode_MODE_UNKNOWN
#define _OutputMode_MAX OutputMode_VTPROTO_REALTIME
#define _OutputMode_ARRAYSIZE ((OutputMode)(OutputMode_VTPROTO_REALTIME + 1))

#define _MotorType_MIN MotorType_MOTOR_TYPE_UNKNOWN
#define _MotorType_MAX MotorType_ULTRASONIC
#define _MotorType_ARRAYSIZE ((MotorType)(MotorType_ULTRASONIC + 1))

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ChannelConfig_init_default \
  { 0, _MotorType_MIN, false, 0 }
#define DisplayConfig_init_default       \
  {                                      \
    _OutputMode_MIN, 0, { {NULL}, NULL } \
  }
#define AvailableConfigOptions_init_default \
  { {{NULL}, NULL}, 0 }
#define ReqSetOutputMode_init_default \
  { _OutputMode_MIN }
#define ReqSetChannelConfig_init_default \
  { false, ChannelConfig_init_default }
#define ChannelConfig_init_zero \
  { 0, _MotorType_MIN, false, 0 }
#define DisplayConfig_init_zero          \
  {                                      \
    _OutputMode_MIN, 0, { {NULL}, NULL } \
  }
#define AvailableConfigOptions_init_zero \
  { {{NULL}, NULL}, 0 }
#define ReqSetOutputMode_init_zero \
  { _OutputMode_MIN }
#define ReqSetChannelConfig_init_zero \
  { false, ChannelConfig_init_zero }

/* Field tags (for use in manual encoding/decoding) */
#define AvailableConfigOptions_motor_types_tag 1
#define AvailableConfigOptions_variable_voltage_tag 2
#define ChannelConfig_channel_number_tag 1
#define ChannelConfig_motor_type_tag 2
#define ChannelConfig_voltage_tag 3
#define DisplayConfig_output_mode_tag 1
#define DisplayConfig_number_of_channels_tag 2
#define DisplayConfig_channel_configs_tag 3
#define ReqSetOutputMode_output_mode_tag 1
#define ReqSetChannelConfig_channel_config_tag 1

/* Struct field encoding specification for nanopb */
#define ChannelConfig_FIELDLIST(X, a)               \
  X(a, STATIC, SINGULAR, UINT32, channel_number, 1) \
  X(a, STATIC, SINGULAR, UENUM, motor_type, 2)      \
  X(a, STATIC, OPTIONAL, FLOAT, voltage, 3)
#define ChannelConfig_CALLBACK NULL
#define ChannelConfig_DEFAULT NULL

#define DisplayConfig_FIELDLIST(X, a)                   \
  X(a, STATIC, SINGULAR, UENUM, output_mode, 1)         \
  X(a, STATIC, SINGULAR, UINT32, number_of_channels, 2) \
  X(a, CALLBACK, REPEATED, MESSAGE, channel_configs, 3)
#define DisplayConfig_CALLBACK pb_default_field_callback
#define DisplayConfig_DEFAULT NULL
#define DisplayConfig_channel_configs_MSGTYPE ChannelConfig

#define AvailableConfigOptions_FIELDLIST(X, a)    \
  X(a, CALLBACK, REPEATED, UENUM, motor_types, 1) \
  X(a, STATIC, SINGULAR, BOOL, variable_voltage, 2)
#define AvailableConfigOptions_CALLBACK pb_default_field_callback
#define AvailableConfigOptions_DEFAULT NULL

#define ReqSetOutputMode_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, UENUM, output_mode, 1)
#define ReqSetOutputMode_CALLBACK NULL
#define ReqSetOutputMode_DEFAULT NULL

#define ReqSetChannelConfig_FIELDLIST(X, a) \
  X(a, STATIC, OPTIONAL, MESSAGE, channel_config, 1)
#define ReqSetChannelConfig_CALLBACK NULL
#define ReqSetChannelConfig_DEFAULT NULL
#define ReqSetChannelConfig_channel_config_MSGTYPE ChannelConfig

extern const pb_msgdesc_t ChannelConfig_msg;
extern const pb_msgdesc_t DisplayConfig_msg;
extern const pb_msgdesc_t AvailableConfigOptions_msg;
extern const pb_msgdesc_t ReqSetOutputMode_msg;
extern const pb_msgdesc_t ReqSetChannelConfig_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ChannelConfig_fields &ChannelConfig_msg
#define DisplayConfig_fields &DisplayConfig_msg
#define AvailableConfigOptions_fields &AvailableConfigOptions_msg
#define ReqSetOutputMode_fields &ReqSetOutputMode_msg
#define ReqSetChannelConfig_fields &ReqSetChannelConfig_msg

/* Maximum encoded size of messages (where known) */
/* DisplayConfig_size depends on runtime parameters */
/* AvailableConfigOptions_size depends on runtime parameters */
#define ChannelConfig_size 13
#define ReqSetChannelConfig_size 15
#define ReqSetOutputMode_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
