/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_TACTILE_DISPLAY_PB_H_INCLUDED
#define PB_TACTILE_DISPLAY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _OutputMode {
  OutputMode_MODE_UNKNOWN = 0,
  OutputMode_VTPROTO_TACTON = 1,
  OutputMode_VTPROTO_REALTIME = 2,
  OutputMode_VTPROTO_TACTON_HARDCODED = 3
} OutputMode;

typedef enum _MotorType {
  MotorType_MOTOR_TYPE_UNKNOWN = 0,
  MotorType_ERM = 1,
  MotorType_LRA = 2,
  MotorType_PIEZO = 3,
  MotorType_PNEUMATIC = 4,
  MotorType_ULTRASONIC = 5
} MotorType;

/* Struct definitions */
typedef struct _AvailableDisplayConfigOptions {
  pb_callback_t output_modes;
} AvailableDisplayConfigOptions;

typedef struct _ReqPlayTactonFile {
  pb_callback_t filename;
} ReqPlayTactonFile;

typedef struct _AvailableChannelConfigOptions {
  pb_callback_t motor_types;
  bool variable_voltage;
} AvailableChannelConfigOptions;

typedef struct _ChannelConfig {
  uint32_t channel_number;
  MotorType motor_type;
  bool has_voltage;
  float voltage;
} ChannelConfig;

typedef struct _DisplayConfig {
  OutputMode output_mode;
  uint32_t number_of_channels;
  pb_callback_t channel_configs;
} DisplayConfig;

typedef struct _ReqSetDisplayConfig {
  OutputMode output_mode;
} ReqSetDisplayConfig;

typedef struct _TactonFileInformation {
  pb_callback_t filename;
  pb_callback_t pattern_name;
  pb_callback_t author;
  uint32_t duration_ms;
  uint32_t n_instructions;
  uint32_t n_channels;
} TactonFileInformation;

typedef struct _TactonFileInformationList {
  uint32_t number_of_messages;
  pb_callback_t file_information;
} TactonFileInformationList;

typedef struct _AvailableConfigurationOptions {
  bool has_display_config_options;
  AvailableDisplayConfigOptions display_config_options;
  bool has_channel_config_options;
  AvailableChannelConfigOptions channel_config_options;
} AvailableConfigurationOptions;

typedef struct _ReqSetChannelConfig {
  bool has_channel_config;
  ChannelConfig channel_config;
} ReqSetChannelConfig;

/* Helper constants for enums */
#define _OutputMode_MIN OutputMode_MODE_UNKNOWN
#define _OutputMode_MAX OutputMode_VTPROTO_TACTON_HARDCODED
#define _OutputMode_ARRAYSIZE \
  ((OutputMode)(OutputMode_VTPROTO_TACTON_HARDCODED + 1))

#define _MotorType_MIN MotorType_MOTOR_TYPE_UNKNOWN
#define _MotorType_MAX MotorType_ULTRASONIC
#define _MotorType_ARRAYSIZE ((MotorType)(MotorType_ULTRASONIC + 1))

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ChannelConfig_init_default \
  { 0, _MotorType_MIN, false, 0 }
#define DisplayConfig_init_default       \
  {                                      \
    _OutputMode_MIN, 0, { {NULL}, NULL } \
  }
#define AvailableChannelConfigOptions_init_default \
  { {{NULL}, NULL}, 0 }
#define AvailableDisplayConfigOptions_init_default \
  {                                                \
    { {NULL}, NULL }                               \
  }
#define AvailableConfigurationOptions_init_default            \
  {                                                           \
    false, AvailableDisplayConfigOptions_init_default, false, \
        AvailableChannelConfigOptions_init_default            \
  }
#define ReqSetDisplayConfig_init_default \
  { _OutputMode_MIN }
#define ReqSetChannelConfig_init_default \
  { false, ChannelConfig_init_default }
#define TactonFileInformation_init_default \
  { {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0 }
#define TactonFileInformationList_init_default \
  {                                            \
    0, { {NULL}, NULL }                        \
  }
#define ReqPlayTactonFile_init_default \
  {                                    \
    { {NULL}, NULL }                   \
  }
#define ChannelConfig_init_zero \
  { 0, _MotorType_MIN, false, 0 }
#define DisplayConfig_init_zero          \
  {                                      \
    _OutputMode_MIN, 0, { {NULL}, NULL } \
  }
#define AvailableChannelConfigOptions_init_zero \
  { {{NULL}, NULL}, 0 }
#define AvailableDisplayConfigOptions_init_zero \
  {                                             \
    { {NULL}, NULL }                            \
  }
#define AvailableConfigurationOptions_init_zero            \
  {                                                        \
    false, AvailableDisplayConfigOptions_init_zero, false, \
        AvailableChannelConfigOptions_init_zero            \
  }
#define ReqSetDisplayConfig_init_zero \
  { _OutputMode_MIN }
#define ReqSetChannelConfig_init_zero \
  { false, ChannelConfig_init_zero }
#define TactonFileInformation_init_zero \
  { {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0 }
#define TactonFileInformationList_init_zero \
  {                                         \
    0, { {NULL}, NULL }                     \
  }
#define ReqPlayTactonFile_init_zero \
  {                                 \
    { {NULL}, NULL }                \
  }

/* Field tags (for use in manual encoding/decoding) */
#define AvailableDisplayConfigOptions_output_modes_tag 1
#define ReqPlayTactonFile_filename_tag 1
#define AvailableChannelConfigOptions_motor_types_tag 1
#define AvailableChannelConfigOptions_variable_voltage_tag 2
#define ChannelConfig_channel_number_tag 1
#define ChannelConfig_motor_type_tag 2
#define ChannelConfig_voltage_tag 3
#define DisplayConfig_output_mode_tag 1
#define DisplayConfig_number_of_channels_tag 2
#define DisplayConfig_channel_configs_tag 3
#define ReqSetDisplayConfig_output_mode_tag 1
#define TactonFileInformation_filename_tag 1
#define TactonFileInformation_pattern_name_tag 2
#define TactonFileInformation_author_tag 3
#define TactonFileInformation_duration_ms_tag 4
#define TactonFileInformation_n_instructions_tag 5
#define TactonFileInformation_n_channels_tag 6
#define TactonFileInformationList_number_of_messages_tag 1
#define TactonFileInformationList_file_information_tag 2
#define AvailableConfigurationOptions_display_config_options_tag 1
#define AvailableConfigurationOptions_channel_config_options_tag 2
#define ReqSetChannelConfig_channel_config_tag 1

/* Struct field encoding specification for nanopb */
#define ChannelConfig_FIELDLIST(X, a)               \
  X(a, STATIC, SINGULAR, UINT32, channel_number, 1) \
  X(a, STATIC, SINGULAR, UENUM, motor_type, 2)      \
  X(a, STATIC, OPTIONAL, FLOAT, voltage, 3)
#define ChannelConfig_CALLBACK NULL
#define ChannelConfig_DEFAULT NULL

#define DisplayConfig_FIELDLIST(X, a)                   \
  X(a, STATIC, SINGULAR, UENUM, output_mode, 1)         \
  X(a, STATIC, SINGULAR, UINT32, number_of_channels, 2) \
  X(a, CALLBACK, REPEATED, MESSAGE, channel_configs, 3)
#define DisplayConfig_CALLBACK pb_default_field_callback
#define DisplayConfig_DEFAULT NULL
#define DisplayConfig_channel_configs_MSGTYPE ChannelConfig

#define AvailableChannelConfigOptions_FIELDLIST(X, a) \
  X(a, CALLBACK, REPEATED, UENUM, motor_types, 1)     \
  X(a, STATIC, SINGULAR, BOOL, variable_voltage, 2)
#define AvailableChannelConfigOptions_CALLBACK pb_default_field_callback
#define AvailableChannelConfigOptions_DEFAULT NULL

#define AvailableDisplayConfigOptions_FIELDLIST(X, a) \
  X(a, CALLBACK, REPEATED, UENUM, output_modes, 1)
#define AvailableDisplayConfigOptions_CALLBACK pb_default_field_callback
#define AvailableDisplayConfigOptions_DEFAULT NULL

#define AvailableConfigurationOptions_FIELDLIST(X, a)        \
  X(a, STATIC, OPTIONAL, MESSAGE, display_config_options, 1) \
  X(a, STATIC, OPTIONAL, MESSAGE, channel_config_options, 2)
#define AvailableConfigurationOptions_CALLBACK NULL
#define AvailableConfigurationOptions_DEFAULT NULL
#define AvailableConfigurationOptions_display_config_options_MSGTYPE \
  AvailableDisplayConfigOptions
#define AvailableConfigurationOptions_channel_config_options_MSGTYPE \
  AvailableChannelConfigOptions

#define ReqSetDisplayConfig_FIELDLIST(X, a) \
  X(a, STATIC, SINGULAR, UENUM, output_mode, 1)
#define ReqSetDisplayConfig_CALLBACK NULL
#define ReqSetDisplayConfig_DEFAULT NULL

#define ReqSetChannelConfig_FIELDLIST(X, a) \
  X(a, STATIC, OPTIONAL, MESSAGE, channel_config, 1)
#define ReqSetChannelConfig_CALLBACK NULL
#define ReqSetChannelConfig_DEFAULT NULL
#define ReqSetChannelConfig_channel_config_MSGTYPE ChannelConfig

#define TactonFileInformation_FIELDLIST(X, a)       \
  X(a, CALLBACK, SINGULAR, STRING, filename, 1)     \
  X(a, CALLBACK, SINGULAR, STRING, pattern_name, 2) \
  X(a, CALLBACK, SINGULAR, STRING, author, 3)       \
  X(a, STATIC, SINGULAR, UINT32, duration_ms, 4)    \
  X(a, STATIC, SINGULAR, UINT32, n_instructions, 5) \
  X(a, STATIC, SINGULAR, UINT32, n_channels, 6)
#define TactonFileInformation_CALLBACK pb_default_field_callback
#define TactonFileInformation_DEFAULT NULL

#define TactonFileInformationList_FIELDLIST(X, a)       \
  X(a, STATIC, SINGULAR, UINT32, number_of_messages, 1) \
  X(a, CALLBACK, REPEATED, MESSAGE, file_information, 2)
#define TactonFileInformationList_CALLBACK pb_default_field_callback
#define TactonFileInformationList_DEFAULT NULL
#define TactonFileInformationList_file_information_MSGTYPE TactonFileInformation

#define ReqPlayTactonFile_FIELDLIST(X, a) \
  X(a, CALLBACK, SINGULAR, STRING, filename, 1)
#define ReqPlayTactonFile_CALLBACK pb_default_field_callback
#define ReqPlayTactonFile_DEFAULT NULL

extern const pb_msgdesc_t ChannelConfig_msg;
extern const pb_msgdesc_t DisplayConfig_msg;
extern const pb_msgdesc_t AvailableChannelConfigOptions_msg;
extern const pb_msgdesc_t AvailableDisplayConfigOptions_msg;
extern const pb_msgdesc_t AvailableConfigurationOptions_msg;
extern const pb_msgdesc_t ReqSetDisplayConfig_msg;
extern const pb_msgdesc_t ReqSetChannelConfig_msg;
extern const pb_msgdesc_t TactonFileInformation_msg;
extern const pb_msgdesc_t TactonFileInformationList_msg;
extern const pb_msgdesc_t ReqPlayTactonFile_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ChannelConfig_fields &ChannelConfig_msg
#define DisplayConfig_fields &DisplayConfig_msg
#define AvailableChannelConfigOptions_fields &AvailableChannelConfigOptions_msg
#define AvailableDisplayConfigOptions_fields &AvailableDisplayConfigOptions_msg
#define AvailableConfigurationOptions_fields &AvailableConfigurationOptions_msg
#define ReqSetDisplayConfig_fields &ReqSetDisplayConfig_msg
#define ReqSetChannelConfig_fields &ReqSetChannelConfig_msg
#define TactonFileInformation_fields &TactonFileInformation_msg
#define TactonFileInformationList_fields &TactonFileInformationList_msg
#define ReqPlayTactonFile_fields &ReqPlayTactonFile_msg

/* Maximum encoded size of messages (where known) */
/* DisplayConfig_size depends on runtime parameters */
/* AvailableChannelConfigOptions_size depends on runtime parameters */
/* AvailableDisplayConfigOptions_size depends on runtime parameters */
/* AvailableConfigurationOptions_size depends on runtime parameters */
/* TactonFileInformation_size depends on runtime parameters */
/* TactonFileInformationList_size depends on runtime parameters */
/* ReqPlayTactonFile_size depends on runtime parameters */
#define ChannelConfig_size 13
#define ReqSetChannelConfig_size 15
#define ReqSetDisplayConfig_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
