/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_VTPROTO_VTPROTO_PB_H_INCLUDED
#define PB_VTPROTO_VTPROTO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _WaveformType { 
    WaveformType_SINE = 0, 
    WaveformType_SQUARE = 1, 
    WaveformType_TRIANGLE = 2, 
    WaveformType_SAWTOOTH = 3 
} WaveformType;

/* Struct definitions */
typedef struct _FileHeader_CustomHeadersEntry { 
    pb_callback_t key; 
    pb_callback_t value; 
} FileHeader_CustomHeadersEntry;

typedef struct _FileHeader { 
    uint32_t format_version; /* Fixed value for this draft of vtproto: 0 */
    pb_callback_t pattern_name; 
    pb_callback_t author; 
    uint32_t duration_ms; 
    uint32_t n_instructions; 
    uint32_t n_channels; 
    pb_callback_t custom_headers; 
} FileHeader;

typedef struct _InstAddToGroup { 
    uint32_t group_id; 
    pb_callback_t ids_to_be_added; 
} InstAddToGroup;

typedef struct _InstInstantlySetParameter { 
    pb_size_t which_target_id;
    union {
        uint32_t channel_id;
        uint32_t group_id;
    } target_id; 
    pb_size_t which_parameter;
    union {
        float intensity;
        uint32_t frequency_hz;
    } parameter; 
} InstInstantlySetParameter;

typedef struct _InstInterpolateParameter { 
    pb_size_t which_target_id;
    union {
        uint32_t channel_id;
        uint32_t group_id;
    } target_id; 
    uint32_t duration_ms; 
    pb_size_t which_parameter;
    union {
        float intensity;
        uint32_t frequency_hz;
    } parameter; 
} InstInterpolateParameter;

typedef struct _InstSetWaveformType { 
    pb_size_t which_target_id;
    union {
        uint32_t channel_id;
        uint32_t group_id;
    } target_id; 
    WaveformType waveform_type; 
} InstSetWaveformType;

typedef struct _InstWait { 
    uint32_t milliseconds; 
} InstWait;

typedef struct _Instruction { 
    pb_callback_t cb_concrete_instruction;
    pb_size_t which_concrete_instruction;
    union {
        InstAddToGroup add_channels_to_group;
        InstAddToGroup add_groups_to_group;
        InstWait wait;
        InstSetWaveformType set_waveform_type;
        InstInstantlySetParameter set_parameter;
        InstInterpolateParameter interpolate_parameter;
    } concrete_instruction; 
} Instruction;


/* Helper constants for enums */
#define _WaveformType_MIN WaveformType_SINE
#define _WaveformType_MAX WaveformType_SAWTOOTH
#define _WaveformType_ARRAYSIZE ((WaveformType)(WaveformType_SAWTOOTH+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define FileHeader_init_default                  {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}}
#define FileHeader_CustomHeadersEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define Instruction_init_default                 {{{NULL}, NULL}, 0, {InstAddToGroup_init_default}}
#define InstAddToGroup_init_default              {0, {{NULL}, NULL}}
#define InstInstantlySetParameter_init_default   {0, {0}, 0, {0}}
#define InstInterpolateParameter_init_default    {0, {0}, 0, 0, {0}}
#define InstSetWaveformType_init_default         {0, {0}, _WaveformType_MIN}
#define InstWait_init_default                    {0}
#define FileHeader_init_zero                     {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}}
#define FileHeader_CustomHeadersEntry_init_zero  {{{NULL}, NULL}, {{NULL}, NULL}}
#define Instruction_init_zero                    {{{NULL}, NULL}, 0, {InstAddToGroup_init_zero}}
#define InstAddToGroup_init_zero                 {0, {{NULL}, NULL}}
#define InstInstantlySetParameter_init_zero      {0, {0}, 0, {0}}
#define InstInterpolateParameter_init_zero       {0, {0}, 0, 0, {0}}
#define InstSetWaveformType_init_zero            {0, {0}, _WaveformType_MIN}
#define InstWait_init_zero                       {0}

/* Field tags (for use in manual encoding/decoding) */
#define FileHeader_CustomHeadersEntry_key_tag    1
#define FileHeader_CustomHeadersEntry_value_tag  2
#define FileHeader_format_version_tag            1
#define FileHeader_pattern_name_tag              2
#define FileHeader_author_tag                    3
#define FileHeader_duration_ms_tag               4
#define FileHeader_n_instructions_tag            5
#define FileHeader_n_channels_tag                6
#define FileHeader_custom_headers_tag            7
#define InstAddToGroup_group_id_tag              1
#define InstAddToGroup_ids_to_be_added_tag       2
#define InstInstantlySetParameter_channel_id_tag 1
#define InstInstantlySetParameter_group_id_tag   2
#define InstInstantlySetParameter_intensity_tag  3
#define InstInstantlySetParameter_frequency_hz_tag 4
#define InstInterpolateParameter_channel_id_tag  1
#define InstInterpolateParameter_group_id_tag    2
#define InstInterpolateParameter_duration_ms_tag 3
#define InstInterpolateParameter_intensity_tag   4
#define InstInterpolateParameter_frequency_hz_tag 5
#define InstSetWaveformType_channel_id_tag       1
#define InstSetWaveformType_group_id_tag         2
#define InstSetWaveformType_waveform_type_tag    3
#define InstWait_milliseconds_tag                1
#define Instruction_add_channels_to_group_tag    1
#define Instruction_add_groups_to_group_tag      2
#define Instruction_wait_tag                     3
#define Instruction_set_waveform_type_tag        4
#define Instruction_set_parameter_tag            5
#define Instruction_interpolate_parameter_tag    6

/* Struct field encoding specification for nanopb */
#define FileHeader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   format_version,    1) \
X(a, CALLBACK, SINGULAR, STRING,   pattern_name,      2) \
X(a, CALLBACK, SINGULAR, STRING,   author,            3) \
X(a, STATIC,   SINGULAR, UINT32,   duration_ms,       4) \
X(a, STATIC,   SINGULAR, UINT32,   n_instructions,    5) \
X(a, STATIC,   SINGULAR, UINT32,   n_channels,        6) \
X(a, CALLBACK, REPEATED, MESSAGE,  custom_headers,    7)
#define FileHeader_CALLBACK pb_default_field_callback
#define FileHeader_DEFAULT NULL
#define FileHeader_custom_headers_MSGTYPE FileHeader_CustomHeadersEntry

#define FileHeader_CustomHeadersEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define FileHeader_CustomHeadersEntry_CALLBACK pb_default_field_callback
#define FileHeader_CustomHeadersEntry_DEFAULT NULL

#define Instruction_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (concrete_instruction,add_channels_to_group,concrete_instruction.add_channels_to_group),   1) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (concrete_instruction,add_groups_to_group,concrete_instruction.add_groups_to_group),   2) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (concrete_instruction,wait,concrete_instruction.wait),   3) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (concrete_instruction,set_waveform_type,concrete_instruction.set_waveform_type),   4) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (concrete_instruction,set_parameter,concrete_instruction.set_parameter),   5) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (concrete_instruction,interpolate_parameter,concrete_instruction.interpolate_parameter),   6)
#define Instruction_CALLBACK NULL
#define Instruction_DEFAULT NULL
#define Instruction_concrete_instruction_add_channels_to_group_MSGTYPE InstAddToGroup
#define Instruction_concrete_instruction_add_groups_to_group_MSGTYPE InstAddToGroup
#define Instruction_concrete_instruction_wait_MSGTYPE InstWait
#define Instruction_concrete_instruction_set_waveform_type_MSGTYPE InstSetWaveformType
#define Instruction_concrete_instruction_set_parameter_MSGTYPE InstInstantlySetParameter
#define Instruction_concrete_instruction_interpolate_parameter_MSGTYPE InstInterpolateParameter

#define InstAddToGroup_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   group_id,          1) \
X(a, CALLBACK, REPEATED, UINT32,   ids_to_be_added,   2)
#define InstAddToGroup_CALLBACK pb_default_field_callback
#define InstAddToGroup_DEFAULT NULL

#define InstInstantlySetParameter_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UINT32,   (target_id,channel_id,target_id.channel_id),   1) \
X(a, STATIC,   ONEOF,    UINT32,   (target_id,group_id,target_id.group_id),   2) \
X(a, STATIC,   ONEOF,    FLOAT,    (parameter,intensity,parameter.intensity),   3) \
X(a, STATIC,   ONEOF,    UINT32,   (parameter,frequency_hz,parameter.frequency_hz),   4)
#define InstInstantlySetParameter_CALLBACK NULL
#define InstInstantlySetParameter_DEFAULT NULL

#define InstInterpolateParameter_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UINT32,   (target_id,channel_id,target_id.channel_id),   1) \
X(a, STATIC,   ONEOF,    UINT32,   (target_id,group_id,target_id.group_id),   2) \
X(a, STATIC,   SINGULAR, UINT32,   duration_ms,       3) \
X(a, STATIC,   ONEOF,    FLOAT,    (parameter,intensity,parameter.intensity),   4) \
X(a, STATIC,   ONEOF,    UINT32,   (parameter,frequency_hz,parameter.frequency_hz),   5)
#define InstInterpolateParameter_CALLBACK NULL
#define InstInterpolateParameter_DEFAULT NULL

#define InstSetWaveformType_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UINT32,   (target_id,channel_id,target_id.channel_id),   1) \
X(a, STATIC,   ONEOF,    UINT32,   (target_id,group_id,target_id.group_id),   2) \
X(a, STATIC,   SINGULAR, UENUM,    waveform_type,     3)
#define InstSetWaveformType_CALLBACK NULL
#define InstSetWaveformType_DEFAULT NULL

#define InstWait_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   milliseconds,      1)
#define InstWait_CALLBACK NULL
#define InstWait_DEFAULT NULL

extern const pb_msgdesc_t FileHeader_msg;
extern const pb_msgdesc_t FileHeader_CustomHeadersEntry_msg;
extern const pb_msgdesc_t Instruction_msg;
extern const pb_msgdesc_t InstAddToGroup_msg;
extern const pb_msgdesc_t InstInstantlySetParameter_msg;
extern const pb_msgdesc_t InstInterpolateParameter_msg;
extern const pb_msgdesc_t InstSetWaveformType_msg;
extern const pb_msgdesc_t InstWait_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define FileHeader_fields &FileHeader_msg
#define FileHeader_CustomHeadersEntry_fields &FileHeader_CustomHeadersEntry_msg
#define Instruction_fields &Instruction_msg
#define InstAddToGroup_fields &InstAddToGroup_msg
#define InstInstantlySetParameter_fields &InstInstantlySetParameter_msg
#define InstInterpolateParameter_fields &InstInterpolateParameter_msg
#define InstSetWaveformType_fields &InstSetWaveformType_msg
#define InstWait_fields &InstWait_msg

/* Maximum encoded size of messages (where known) */
/* FileHeader_size depends on runtime parameters */
/* FileHeader_CustomHeadersEntry_size depends on runtime parameters */
/* Instruction_size depends on runtime parameters */
/* InstAddToGroup_size depends on runtime parameters */
#define InstInstantlySetParameter_size           12
#define InstInterpolateParameter_size            18
#define InstSetWaveformType_size                 8
#define InstWait_size                            6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
