/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "tactile_display.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ChannelConfig, ChannelConfig, AUTO)

PB_BIND(DisplayConfig, DisplayConfig, AUTO)

PB_BIND(AvailableConfigOptions, AvailableConfigOptions, AUTO)

PB_BIND(ReqSetOutputMode, ReqSetOutputMode, AUTO)

PB_BIND(ReqSetChannelConfig, ReqSetChannelConfig, AUTO)
