/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "vtproto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(FileHeader, FileHeader, AUTO)


PB_BIND(FileHeader_CustomHeadersEntry, FileHeader_CustomHeadersEntry, AUTO)


PB_BIND(Instruction, Instruction, AUTO)


PB_BIND(InstAddToGroup, InstAddToGroup, AUTO)


PB_BIND(InstInstantlySetParameter, InstInstantlySetParameter, AUTO)


PB_BIND(InstInterpolateParameter, InstInterpolateParameter, AUTO)


PB_BIND(InstSetWaveformType, InstSetWaveformType, AUTO)


PB_BIND(InstWait, InstWait, AUTO)




